import java.util.ArrayList;




public class Main {

    //prints the route generated by path
    public static void printRoute(ArrayList<BestPath> currRoute){
        for (int i =0; i<currRoute.size()-1; i++){
            System.out.println("Curr Node: " + currRoute.get(i).NodeID() + " Next Node: " + currRoute.get(i).NextNodeID() + " Time: " + currRoute.get(i).TimeEstimate() );
        }
        System.out.println("Final Node: " + currRoute.get(currRoute.size()-1).NodeID() + " Total Time: " + currRoute.get(currRoute.size()-1).TimeEstimate());
    }

    public static void main(String[] args)  {
        //begin running server
        ServerRouter server = new ServerRouter(8080);

        Runtime.getRuntime().addShutdownHook(new Thread(()->{
            System.out.println("Application is shutting down.");
            server.shutdown();
        }));

    }
}
